/*

Copyright (C) 2022 SE CookBook - All Rights Reserved
You may use, distribute and modify this code under the
terms of the MIT license.
You should have received a copy of the MIT license with
this file. If not, please write to: help.cookbook@gmail.com

*/

export const RECIPE_CATEGORIES = [
  'African',
  'Apple',
  'Asian',
  'Australian',
  'Austrian',
  'Avocado',
  'Bar Cookie',
  'Bass',
  'Bath/Beauty',
  'Beans',
  'Bear',
  'Beef Organ Meats',
  'Beginner Cook',
  'Belgian',
  'Berries',
  'Beverages',
  'Black Beans',
  'Brazilian',
  'Bread Machine',
  'Breads',
  'Breakfast',
  'Breakfast Eggs',
  'Broil/Grill',
  'Brown Rice',
  'Brunch',
  'Cajun',
  'Cambodian',
  'Camping',
  'Canadian',
  'Candy',
  'Canning',
  'Cantonese',
  'Caribbean',
  'Catfish',
  'Cauliflower',
  'Chard',
  'Cheese',
  'Cheesecake',
  'Cherries',
  'Chicken',
  'Chicken Breast',
  'Chicken Livers',
  'Chicken Thigh & Leg',
  'Chilean',
  'Chinese',
  'Chocolate Chip Cookies',
  'Chowders',
  'Christmas',
  'Chutneys',
  'Citrus',
  'Clear Soup',
  'Coconut',
  'Collard Greens',
  'Colombian',
  'Corn',
  'Costa Rican',
  'Crab',
  'Crawfish',
  'Creole',
  'Cuban',
  'Curries',
  'Czech',
  'Dairy Free Foods',
  'Danish',
  'Deep Fried',
  'Deer',
  'Dehydrator',
  'Dessert',
  'Drop Cookies',
  'Duck',
  'Duck Breasts',
  'Dutch',
  'Easy',
  'Ecuadorean',
  'Egg Free',
  'Egyptian',
  'Elk',
  'Ethiopian',
  'European',
  'Filipino',
  'Finnish',
  'For Large Groups',
  'Free Of...',
  'Frozen Desserts',
  'Fruit',
  'Gelatin',
  'Georgian',
  'German',
  'Goose',
  'Grains',
  'Greek',
  'Greens',
  'Gumbo',
  'Halibut',
  'Halloween',
  'Ham',
  'Hanukkah',
  'Hawaiian',
  'Healthy',
  'High Fiber',
  'High In...',
  'High Protein',
  'Homeopathy/Remedies',
  'Household Cleaner',
  'Hunan',
  'Hungarian',
  'Icelandic',
  'Indonesian',
  'Inexpensive',
  'Iraqi',
  'Japanese',
  'Jellies',
  'Kid Friendly',
  'Kiwifruit',
  'Korean',
  'Kosher',
  'Lactose Free',
  'Lamb/Sheep',
  'Lebanese',
  'Lemon',
  'Lentil',
  'Lime',
  'Lobster',
  'Long Grain Rice',
  'Low Cholesterol',
  'Low Protein',
  'Lunch/Snacks',
  'Mahi Mahi',
  'Malaysian',
  'Mango',
  'Manicotti',
  'Meat',
  'Meatballs',
  'Meatloaf',
  'Medium Grain Rice',
  'Melons',
  'Mexican',
  'Microwave',
  'Mixer',
  'Moose',
  'Moroccan',
  'Mussels',
  'Native American',
  'Nepalese',
  'New Zealand',
  'Nigerian',
  'No Cook',
  'No Shell Fish',
  'Norwegian',
  'Nuts',
  'Octopus',
  'One Dish Meal',
  'Onions',
  'Orange Roughy',
  'Oranges',
  'Oven',
  'Oysters',
  'Pakistani',
  'Palestinian',
  'Papaya',
  'Pasta Shells',
  'Peanut Butter',
  'Pears',
  'Penne',
  'Pennsylvania Dutch',
  'Peppers',
  'Perch',
  'Pheasant',
  'Pie',
  'Pineapple',
  'Plums',
  'Polish',
  'Polynesian',
  'Pork',
  'Portuguese',
  'Pot Pie',
  'Potato',
  'Potluck',
  'Poultry',
  'Pressure Cooker',
  'Puerto Rican',
  'Punch Beverage',
  'Quail',
  'Quick Breads',
  'Rabbit',
  'Raspberries',
  'Refrigerator',
  'Rice',
  'Roast',
  'Roast Beef',
  'Russian',
  'Salad Dressings',
  'Sauces',
  'Savory',
  'Savory Pies',
  'Scandinavian',
  'Scones',
  'Scottish',
  'Shakes',
  'Short Grain Rice',
  'Small Appliance',
  'Smoothies',
  'Sourdough Breads',
  'South African',
  'South American',
  'Southwest Asia (Middle East)',
  'Southwestern U.S.',
  'Soy/Tofu',
  'Spaghetti',
  'Spanish',
  'Spicy',
  'Spinach',
  'Spreads',
  'Spring',
  'Squid',
  "St. Patrick's Day",
  'Steak',
  'Steam',
  'Stew',
  'Stir Fry',
  'Stocks',
  'Stove Top',
  'Strawberry',
  'Summer',
  'Summer Dip',
  'Swedish',
  'Sweet',
  'Swiss',
  'Szechuan',
  'Tarts',
  'Tempeh',
  'Tex Mex',
  'Thai',
  'Thanksgiving',
  'Tilapia',
  'Toddler Friendly',
  'Tropical Fruits',
  'Trout',
  'Tuna',
  'Turkey Breasts',
  'Turkish',
  'Veal',
  'Vegan',
  'Vegetable',
  'Venezuelan',
  'Very Low Carbs',
  'Vietnamese',
  'Weeknight',
  'Welsh',
  'White Rice',
  'Whitefish',
  'Whole Chicken',
  'Whole Duck',
  'Whole Turkey',
  'Wild Game',
  'Winter',
  'Yam/Sweet Potato',
  'Yeast Breads',
]

export const RECIPE_COOKTIME = [
  '< 15 Mins',
  '< 30 Mins',
  '< 60 Mins',
  '< 4 Hours',
]
