name: Python Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:  # Global environment variables
      ATLAS_URI: "mongodb+srv://se-group23:TfE2up8EBCGvlv73@cluster0.ichs9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      DB_NAME: "CookBook"
      GROQ_API_KEY: "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"
      PORT: "8000"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies for testing
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest fastapi

    - name: Install API dependencies
      run: |
        cd api
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        coverage run -m pytest ./tests/
        coverage report -m

    - name: Upload coverage report
      if: success()
      env:  # Set GITHUB_TOKEN for Coveralls
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install coveralls
        coveralls
