name: Python Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:  # Global environment variables
      ATLAS_URI: "mongodb+srv://prajwaljungthapa:Hello123@cookbook.ma3vl.mongodb.net/?retryWrites=true&w=majority&appName=cookbook"
      DB_NAME: "cookbook"
      GROQ_API_KEY: "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"
      PORT: "8000"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies for testing
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest fastapi

    - name: Install API dependencies
      run: |
        cd api
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        coverage run -m pytest ./tests/
        coverage report -m

    - name: Upload coverage report
      if: success()
      env:  # Set GITHUB_TOKEN for Coveralls
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install coveralls
        coveralls
